version: '3.5'
services:
  minkebox:
    container_name: minkebox
    image: registry.minkebox.net/minkebox/minke
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/minkebox:/minke
    privileged: true
    networks:
      home:
        ipv4_address: ${IP}
networks:
  home:
    name: home
    driver: macvlan
    ipam:
      config:
      - subnet: ${IP}/24
    driver_opts:
      parent: ${NETWORK}
